### ISSUE TITLE
Character Special cards

### ISSUE THREAD

**Issue by Django042** [Kamalisk/arkhamdb#35]
Is it legal to add a second copy of a characters special item to a deck (replacing an existing card)? They look like neutral cards with the printed restriction, only in their owners deck. I couldn't find any rule that explicitly prohibits this. 

If this is legal, please add this feature to the deckbuilder.

**Comment by mattsigal** [comment]
It is not legal.

**Comment by Django042** [comment]
I expected as much, but can you quote the appropriate ruling (or which page of the reference i can find it)?

**Comment by Kamalisk** [comment]
Yep not legal. It is because they are not supposed to have an xp cost of 0, they should have no xp bar at all. So then they can only be included if told to by the investigators card. This is not actually mentioned in the rules but was stated by the designer that it was a mistake in the core set printing. You will noticed the Dunwich cards are correct.
