### ISSUE TITLE
Import not working or missing information

### ISSUE THREAD

**Issue by Django042** [Kamalisk/arkhamdb#36]
I can neither import decks through "copy/paste" nor as file. I tried both with Firefox and Internet Explorer.

File Import Error:
Notice: Undefined index: faction_code in /opt/nrdb/adb/src/AppBundle/Controller/BuilderController.php on line 209

When using Copy/paste, i can copy the deck of a friend, but if i hit "parse", nothing happens.

Theres also no further information about importing, like special formatings of the text, etc.

**Comment by Kamalisk** [comment]
The import tries it's best to guess what cards are included based on name. I never updated it for arkham so it was stillt trying to get a faction. I will make it at least work at first, but I need to add some extra logic for XP cards since they have duplicate names. No matter what I do, some manual adjustments would probably be needed.

**Comment by Kamalisk** [comment]
It should work mostly now. If it misses any cards it should be easy enough to save and fix the deck. It will not work without an investigator though. which just had to be in the text by name.

**Comment by Django042** [comment]
Thanks, the txt import is working, however the copy/paste parse function still does nothing. I personally don't need it, i can create an empty text file and copy the deck in there.

**Comment by Kamalisk** [comment]
Do a proper reload and it should work. If it doesn't let me know what format of text you are pasting into it.
