### ISSUE TITLE
Focus search box on homepage

### ISSUE THREAD

**Issue by mizlan** [Kamalisk/arkhamdb#429]
Could the search box be focused on the homepage? Much of the time, when I go to the site I'm trying to search for a card, so auto-focusing the search box would be super helpful, so I don't have to reach for the mouse.

**Comment by haakenlid** [comment]
It's trivial to implement this. One simply adds the `autofocus` html property to the search input element.

However, this feature should be reserved for dedicated search pages. Google search uses it. Wikipedia uses it only on the root page. Autofocus is also often used for the username input on login pages. You'll find very few other good uses of autofocus on search inputs on the web. 

While you might use the search box more than 50% of all your page views, that is not enough to justify implementing autofocus for everyone. Autofocus should be reserved for pages where 99%-100% of all visits use the search box. The reason for this is that when the page hijacks your focus when you don't expect it, users get very very annoyed. Even more so if you use keyboard navigation instead of mouse, or a touch screen (where autofocus will prompt the on screen keyboard to pop up) or assistive technology.

I don't think the homepage or any other page on arkhamdb would benefit from autofocus on the search input.

**Comment by haakenlid** [comment]
If you really think this would be useful for you, it's possible to get the same functionality using a user script with the TamperMonkey browser extension. Here's an example of such a user script:
https://github.com/jabbalaci/AutoFocus/blob/master/auto_focus.user.js

**Comment by mizlan** [comment]
Thank you! A script like this was exactly what I would like.
