### ISSUE TITLE
Cards/Rules page should be updated with info from official FAQ

### ISSUE THREAD

**Issue by sacrelicious2** [Kamalisk/arkhamdb#61]
We have a new FAQ that erratas some rules and cards.  FAQ can be found here: https://www.fantasyflightgames.com/en/products/arkham-horror-the-card-game/

**Comment by soulb1ight** [comment]
Forced text for Smite the Wicked should read:
**Forced** – When the game ends, if attached enemy is in play: Zoey Samaras suffers 1 mental trauma.

Forced text for Searching for Izzie should read:
**Forced** – When the game ends, if Searching for Izzie is in play: Jenny Barnes suffers 1 mental trauma.

**Comment by soulb1ight** [comment]
Rules Reference for Costs, third bullet point should read:

When a player is exhausting, sacrificing, or otherwise using cards to pay costs, only cards that are in play and under that player's control may be used, unless the cost specifies an out-of-play state.

Rules Reference for Elimination should have a Step 0:

0. For the purposes of resolving weakness cards, the game has ended for the eliminated investigator. Trigger any "when the game ends" abilities on each weakness the eliminated investigator owns that is in play. Then, remove those weaknesses from the game.

Rules Reference for Weakness, fifth bullet point should read:

If a weakness is added to a player's deck, hand, or threat area during the play of a scenario, that weakness remains a part of that investigator's deck for the rest of the campaign. (Unless it is removed from the campaign by a card ability or scenario resolution.)

**Comment by soulb1ight** [comment]
Add the following Definitions and Terms, perhaps to the Glossary?

**“Record in your Campaign Log...”**
Often the players will be instructed to record a key phrase in the Campaign
Log. This should be written under “Campaign Notes” unless specified
otherwise. Because the players may be instructed to check the Campaign
Log for this phrase at a later time in the campaign, the indicated phrase
should be recorded as it appears, without alteration.
_For example: If the players are instructed to record in the Campaign Log that
“the investigators were four hours late,” this shouldn’t be rewritten as “the
investigators were pretty late,” because the exact number of hours might be
important in a later scenario._

**“Remember that...”**
Sometimes a scenario card will instruct the investigators to “remember”
a key phrase, often based on an action they have taken or a decision they
have made within that scenario. This phrase may come up later during that
scenario, and may trigger additional or different effects. There is no need
to record this phrase in the Campaign Log, because it will only ever matter
during that scenario, or during that scenario’s resolution. The players do not
need to “remember” any such instruction beyond the end of the scenario in
which it appears.

**Signature Cards**
An investigator’s “signature cards” are the cards that are only available to
that investigator, and cannot be included in another investigator’s deck. This
includes player cards with the text “(Investigator Name) deck only,” as well
as non-basic weaknesses that are listed under “Deckbuilding Requirements”
and therefore can only be included in that investigator’s deck.

Signature cards are governed by the following _additional_ rules:

- The number of each signature card listed under an investigator’s
“Deckbuilding Requirements” is the exact number of copies of that
card that is to be included in that investigator’s deck. If no number is
specified, that number is 1.
_For example: Under “Deckbuilding Requirements” for Roland Banks,
the following cards are listed: “Roland’s .38 Special, Cover Up, 1 random
basic weakness.” Roland Banks must include exactly 1 copy of his
signature cards—Roland’s .38 Special and Cover Up. He is not permitted
to include more than 1 copy of either of these cards._

- An investigator’s signature cards cannot be traded or given to other
investigators.
_For example: Roland has the Roland’s .38 Special card in play. He has
the card “Teamwork” which can allow investigators at the same location
to trade or give assets among one another. However, because Roland’s .38
Special is one of Roland’s signature cards, he cannot give it to another
investigator._

**Comment by jayelbird** [comment]
I've put in a pull request that updates the rules page.

**Comment by Kamalisk** [comment]
added support for others to update card faqs, I expect those will get filled in soon, and the rules were updated so will close this.

**Comment by mattsigal** [comment]
I feel left in the dark - where on arkhamdb are the card FAQs?

**Comment by Kamalisk** [comment]
on the cards themselves.

**Comment by mattsigal** [comment]
Ohhh, finally found one (on Double or Nothing). Cool. Are these just for official clarifications? Or is there a way to add an FAQ entry for a particular card on the page itself?
