### ISSUE TITLE
Subject 5U-21 - Contains forbidden cards (cards not permitted by Faction or Agenda)

### ISSUE THREAD

**Issue by sugartwig** [Kamalisk/arkhamdb#631]
Subject 5U-21 decks (from The Blob That Ate Everything ELSE!) can't be saved and return an error, even after multiple attempts.
10 assets of each color for testing (7+ Class cards of each required).
![image](https://github.com/Kamalisk/arkhamdb/assets/111081715/0f96a94e-564c-4e59-99cb-1745fd384344)

**Comment by Balthazar-03** [comment]
The deck can be saved, it just can't be published. Suzi has 2 conflicting deckbuilding restrictions that are causing these issues.
One, it needs to have the card "Ravenous" in the deck. No issue there.
The issue comes from the fact that Suzi **can't** have **any** permanents. **Ravenous is a permanent**.
For those who will fix this, I'm gonna say thanks ahead of time! Hope this bit of info helps 😄

**Comment by Kamalisk** [comment]
I think someone managed to fix this, let me know if its not.
