### ISSUE TITLE
Oauth not working

### ISSUE THREAD

**Issue by LironCareto** [Kamalisk/arkhamdb#663]
The authentication screen https://arkhamdb.com/oauth/v2/auth_login is not working. When entered the credentials, it returns to the login screen without authorization. This makes applications that connect to Arkhamdb.com not work.

To reproduce.
Enter https://arkhamdb.com/oauth/v2/auth_login in the browser (desktop or mobile) and try to log in.

**Comment by zzorba** [comment]
Do you have an app id + secret?  The OAuth flow still seems to be working for the ArkhamCards app, at least on Android.

You have to reach out to kamalisk via email to request credentials to connect credentials to support OAuth on your own site though.

**Comment by LironCareto** [comment]
It's not my own site. I discovered this while using Arkham Cards, which stopped working. It worked before but today it requested re-authentication, and the authentication in Arkhamdb didn't work. And there is definitely something not working in Arkhamdb because the normal login does not work after logging out. It worked when I reset the password, but if I log out and try to log in again, the new password does not work anymore.

**Comment by zzorba** [comment]
So on iOS I know there are issues with the way the browsers store cookies in apps. It makes oauth difficult since each app has its own silo, and there's no way to log out.

On android there is sometimes memory pressure on the phone that breaks the app. Restarting the phone might help, and making sure you are using chrome browser (opera and Firefox sometimes have issues when embedded in other apps).

Email me in the app and I can try to debug further.

**Comment by Kamalisk** [comment]
I would guess you solved this issue
