### ISSUE TITLE
Pop-up card previews

### ISSUE THREAD

**Issue by mplain** [Kamalisk/arkhamdb#8]
- For locations, make the Revealed side show in pop-up previews, not the Back side.

- For locations, make rules text go first, then flavor text. There should be some space left between the vertical line and the rules text (see Parlor).

- Victory points don't show up in the pop-up preview.

- The [free] icon doesn't show up in pop-up previews and on the Rules page.

- "Clues: -" shows up in pop-ups, but not on the card page proper.

![parlor](https://cloud.githubusercontent.com/assets/7605827/20209419/6228cd1c-a805-11e6-8b1c-1ce0741ebbaf.png)

**Comment by Kamalisk** [comment]
I disagree with the revealed side of locations in pop ups btw. It is intentional. I mean hovering over a link is different from actively clicking through to see the locations. 
Victory points not showing up is also slightly intentional, there are some things which don't show up in the pop up (I might change it so victory does though)

**Comment by mplain** [comment]
Okay, then another suggestion: Make the subname show up when browsing cards. Those six copies of Arkham Woods are confusing if you just want to check out a particular one...

**Comment by Kamalisk** [comment]
With spoilers added, adding more stuff to the tooltips so above should be sorted now.
